package constants

// log_templates.go 集中定义全部日志格式字符串（≥25 条）。
const (
	LOG_USER_REGISTER_START         = "User register start"
	LOG_USER_REGISTER_SUCCESS       = "User register success"
	LOG_USER_LOGIN_SUCCESS          = "User login success"
	LOG_USER_LOGIN_FAILED           = "User login failed"
	LOG_USER_PROFILE_UPDATED        = "User profile updated"
	LOG_PACKAGE_CREATED             = "Package created"
	LOG_PACKAGE_UPDATED             = "Package updated"
	LOG_PACKAGE_ITEM_ADDED          = "PackageItem added"
	LOG_PACKAGE_ITEM_UPDATED        = "PackageItem updated"
	LOG_EXAMINEE_CREATED            = "Examinee created"
	LOG_EXAMINEE_IMPORTED           = "Examinee batch imported"
	LOG_EXAMINEE_UPDATED            = "Examinee updated"
	LOG_REGISTRATION_CREATED        = "Registration created"
	LOG_REGISTRATION_STATUS_CHANGED = "Registration status changed"
	LOG_EXAM_RESULT_ENTERED         = "ExamResult entered"
	LOG_EXAM_RESULT_REVIEWED        = "ExamResult reviewed"
	LOG_EXAM_RESULT_ABNORMAL        = "ExamResult abnormal detected"
	LOG_REPORT_DRAFTED              = "Report drafted"
	LOG_REPORT_GENERATED            = "Report generated"
	LOG_REPORT_REVIEWED             = "Report reviewed"
	LOG_REPORT_PUBLISHED            = "Report published"
	LOG_REPORT_PUBLISH_FAILED       = "Report publish failed"
	LOG_REPORT_PDF_GENERATED        = "Report PDF generated"
	LOG_ABNORMAL_METRIC_CREATED     = "AbnormalMetric created"
	LOG_ABNORMAL_METRIC_FOLLOWUP    = "AbnormalMetric follow-up updated"
	LOG_ENTERPRISE_CREATED          = "Enterprise created"
	LOG_GROUP_ORDER_CREATED         = "GroupOrder created"
	LOG_GROUP_ORDER_DELIVERED       = "GroupOrder report delivered"
	LOG_STATS_DASHBOARD             = "Stats dashboard generated"
	LOG_FILE_UPLOADED               = "File uploaded"
	LOG_RATE_LIMITED                = "Request rate limited"
	LOG_REQUEST_START               = "Request start"
	LOG_REQUEST_FINISH              = "Request finish"
	LOG_PANIC_RECOVERED             = "Panic recovered"
	LOG_DB_INITIALIZED              = "Database initialized"
	LOG_SERVER_STARTED              = "Server started"
	LOG_SERVER_SHUTDOWN             = "Server shutdown"
)
